name: Build APK

on:
  push:
    branches:
      - main  # Запускать при пуше в main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout репозитория
      uses: actions/checkout@v3

    - name: Установка зависимостей
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip git zip unzip openjdk-17-jdk
        pip3 install --upgrade pip
        pip3 install buildozer

    - name: Кеширование кэша Buildozer
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer
        restore-keys: |
          ${{ runner.os }}-buildozer

    - name: Сборка APK
      run: |
        buildozer -v android debug

    - name: Загрузка APK как артефакт
      uses: actions/upload-artifact@v3
      with:
        name: GemClicker-APK
        path: bin/*.apk